name: Build, Scan, and Publish Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-scan-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/julienlonge/ue19-lab-05/my-image:latest .

    - name: Scan Docker image for vulnerabilities
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: ghcr.io/julienlonge/ue19-lab-05/my-image:latest
        format: table          
        exit-code: 0 
        ignore-unfixed: true

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Étape 5 : Publier l'image Docker
    - name: Push Docker image
      run: |
        docker push ghcr.io/julienlonge/ue19-lab-05/my-image:latest
